version: '3.8'

services:

  web:
    container_name: digital-library-web
 
    build: .
    ports:
     
      - "8080:8080"
      
    environment:
 
      - ConnectionStrings__DefaultConnection=Server=db;Database=DigitalLibraryDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True
    
      - Authentication__Google__ClientId=145781155123-3bem58lk6j4594r2jif3eqfgenvc47tj.apps.googleusercontent.com
      - Authentication__Google__ClientSecret=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
   
    depends_on:
      - db

 
  db:
    container_name: digital-library-db
 
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
     
      - "1433:1433"
    environment:
   
      - ACCEPT_EULA=Y
    
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}