version: '3.8'

services:

  db:
    container_name: digital-library-db-postgres
    image: postgres:latest 
    environment:
      - POSTGRES_DB=DigitalLibraryDb
      - POSTGRES_USER=sa
    
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      
      - "5432:5432" 
    volumes:
    
    - postgres_data:/var/lib/postgresql

  
  web:
    container_name: digital-library-web
    build: .
    ports:
      - "8080:8080"
    environment:
                         
      - ConnectionStrings__DefaultConnection=Host=digital-library-db-postgres;Port=5432;Database=DigitalLibraryDb;Username=sa;Password=${DB_PASSWORD}
      - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID}
      - Authentication__Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db

volumes:
  postgres_data: